"""Phase 8 Scoring-Integrity Audit

Verifies that the VisionGuard scoring pipeline is genuinely dynamic
and that no score, confidence, status, or recommendation is hard-coded
or merely renamed from another value.

Checks:
  1. Quality score comes from the ML pipeline (model → calibrator → score)
  2. Analytics readiness is independently calculated from quality_score + issues
  3. Issue confidence is computed by the detector, not hard-coded per image
  4. No hard-coded production values in backend or frontend
  5. Representative images produce logically different scores
  6. Frontend displays exact API values
"""

from __future__ import annotations

import json
import math
import os
import random
from pathlib import Path

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Backend imports
# ---------------------------------------------------------------------------
from apps.ml.inference import predict_quality, _fallback_score, _estimate_confidence
from apps.ml.readiness import calculate_analytics_readiness, get_readiness_status
from apps.ml.issue_detector import detect_issues, build_issue
from apps.ml.calibration import (
    apply_calibration,
    get_quality_assessment,
    get_quality_recommendation,
    QUALITY_BANDS,
)
from apps.ml.context_definitions import get_context_impacts
from apps.ml.explainability import generate_issue_explanations


# =========================================================================
# 1. Quality score is generated by the pipeline, not hard-coded
# =========================================================================

class TestQualityScoreGeneration:
    """Verify that quality_score is computed dynamically from features."""

    def test_model_path_changes_score(self):
        """Different input features produce different quality scores."""
        # Use widely different feature values to ensure the model differentiates
        features_a = {"brightness": 200, "contrast": 80, "sharpness": 300, "saturation": 80, "edge_density": 0.40}
        features_b = {"brightness": 20, "contrast": 5, "sharpness": 2, "saturation": 2, "edge_density": 0.001}

        all_a = {"sharpness": 300, "brightness": 200, "contrast": 80, "noise_estimate": 5, "entropy": 6.5, "saturation": 80,
                 "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 30, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}
        all_b = {"sharpness": 2, "brightness": 20, "contrast": 5, "noise_estimate": 50, "entropy": 1, "saturation": 2,
                 "underexposure_pct": 60, "overexposure_pct": 0, "edge_density": 0.2, "dynamic_range": 10, "colorfulness": 1, "texture_complexity": 0.5}

        result_a = predict_quality(features_a, all_a)
        result_b = predict_quality(features_b, all_b)

        # Scores must differ between different inputs
        assert result_a["quality_score"] != result_b["quality_score"], (
            f"Quality scores should differ for different inputs: "
            f"input_a={result_a['quality_score']}, input_b={result_b['quality_score']}"
        )

    def test_quality_score_comes_from_pipeline_not_copy(self):
        """quality_score and analytics_readiness_score are NOT the same value."""
        features = {"brightness": 100, "contrast": 40, "sharpness": 80, "saturation": 30, "edge_density": 0.10}
        all_feats = {"sharpness": 80, "brightness": 100, "contrast": 40, "noise_estimate": 12, "entropy": 5.5, "saturation": 30,
                     "underexposure_pct": 8, "overexposure_pct": 3, "edge_density": 8, "dynamic_range": 100, "colorfulness": 20, "texture_complexity": 18}

        result = predict_quality(features, all_feats)

        # They can be different (readiness = quality - penalties)
        # They are only equal when there are zero issues
        issues = detect_issues(all_feats)
        if issues:
            assert result["quality_score"] != result["analytics_readiness_score"], (
                f"With {len(issues)} issues, quality_score ({result['quality_score']}) "
                f"should differ from readiness_score ({result['analytics_readiness_score']})"
            )

    def test_fallback_score_depends_on_features(self):
        """The rule-based fallback score changes with different features."""
        feats_a = {"sharpness": 300, "brightness": 128, "contrast": 50, "saturation": 100, "edge_density": 0.5}
        feats_b = {"sharpness": 0, "brightness": 0, "contrast": 0, "saturation": 0, "edge_density": 0}

        score_a = _fallback_score(feats_a)
        score_b = _fallback_score(feats_b)

        assert score_a > score_b
        assert 0 <= score_a <= 100
        assert 0 <= score_b <= 100

    def test_confidence_estimation_is_dynamic(self):
        """analysis_confidence varies based on model tree agreement."""
        # When model is loaded, confidence comes from _estimate_confidence
        # When no model, it returns 70.0 (rule-based fallback)
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}

        result = predict_quality(features, all_feats)
        # Confidence is a float between 0 and 100
        assert isinstance(result["analysis_confidence"], float)
        assert 0 <= result["analysis_confidence"] <= 100

    def test_raw_prediction_is_independent(self):
        """raw_prediction is the model's output before calibration."""
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}

        result = predict_quality(features, all_feats)
        assert "raw_prediction" in result
        assert isinstance(result["raw_prediction"], float)
        # raw_prediction may differ from quality_score after calibration
        # (they can also be close, but we verify the field exists and is numeric)


# =========================================================================
# 2. Analytics readiness is independently calculated
# =========================================================================

class TestReadinessIndependence:
    """Verify that analytics_readiness_score is NOT simply quality_score renamed."""

    def test_readiness_differs_from_quality_with_issues(self):
        """When issues exist, readiness < quality_score due to penalties."""
        quality_score = 80.0
        issues = [
            {"type": "insufficient_sharpness", "severity": "high", "metric": "laplacian_variance", "value": 30, "threshold": 40, "impact": "test", "confidence": 1.0},
            {"type": "underexposure", "severity": "moderate", "metric": "dark_pixel_ratio", "value": 20, "threshold": 25, "impact": "test", "confidence": 1.0},
        ]

        readiness = calculate_analytics_readiness(quality_score, issues)

        assert readiness["score"] < quality_score, (
            f"Readiness ({readiness['score']}) should be less than quality ({quality_score}) "
            f"when issues are present"
        )

    def test_readiness_penalties_are_computed_from_issues(self):
        """Penalties are derived from issue types and severities."""
        quality_score = 80.0
        issues_blur = [{"type": "severe_blur", "severity": "critical"}]
        issues_none = []

        r_blur = calculate_analytics_readiness(quality_score, issues_blur)
        r_none = calculate_analytics_readiness(quality_score, issues_none)

        # Blur penalty should reduce readiness
        assert r_blur["score"] < r_none["score"]
        assert r_blur["blur_penalty"] > 0
        assert r_none["blur_penalty"] == 0

    def test_readiness_status_maps_correctly(self):
        """Status labels match score thresholds."""
        assert get_readiness_status(95) == "HIGHLY READY"
        assert get_readiness_status(80) == "HIGHLY READY"
        assert get_readiness_status(70) == "READY"
        assert get_readiness_status(60) == "READY"
        assert get_readiness_status(50) == "LIMITED READINESS"
        assert get_readiness_status(40) == "LIMITED READINESS"
        assert get_readiness_status(30) == "NOT READY"
        assert get_readiness_status(20) == "NOT READY"
        assert get_readiness_status(10) == "CRITICAL / REJECT"
        assert get_readiness_status(0) == "CRITICAL / REJECT"

    def test_readiness_score_never_negative(self):
        """Readiness score is clamped to [0, 100]."""
        quality_score = 5.0
        issues = [
            {"type": "severe_blur", "severity": "critical"},
            {"type": "underexposure", "severity": "critical"},
            {"type": "image_noise", "severity": "critical"},
            {"type": "severe_visual_degradation", "severity": "critical"},
            {"type": "low_contrast", "severity": "critical"},
        ]

        readiness = calculate_analytics_readiness(quality_score, issues)

        assert readiness["score"] >= 0
        assert readiness["score"] <= 100

    def test_readiness_details_contain_all_penalty_fields(self):
        """The API response includes all 6 readiness detail fields."""
        readiness = calculate_analytics_readiness(70.0, [])
        details = readiness

        assert "base_quality_score" in details
        assert "blur_penalty" in details
        assert "exposure_penalty" in details
        assert "noise_penalty" in details
        assert "corruption_penalty" in details
        assert "information_penalty" in details
        assert details["base_quality_score"] == 70.0

    def test_different_issue_types_apply_different_penalties(self):
        """Different issue types contribute to different penalty categories."""
        quality_score = 80.0

        r_blur = calculate_analytics_readiness(quality_score, [{"type": "severe_blur", "severity": "high"}])
        r_exposure = calculate_analytics_readiness(quality_score, [{"type": "overexposure", "severity": "high"}])
        r_noise = calculate_analytics_readiness(quality_score, [{"type": "image_noise", "severity": "high"}])

        assert r_blur["blur_penalty"] > 0
        assert r_exposure["exposure_penalty"] > 0
        assert r_noise["noise_penalty"] > 0

        # Each should only penalize its own category
        assert r_blur["exposure_penalty"] == 0
        assert r_exposure["blur_penalty"] == 0
        assert r_noise["blur_penalty"] == 0

    def test_readiness_is_independent_from_quality_label(self):
        """Readiness status is independent of quality label."""
        # Two images with same quality_score but different issues
        q = 65.0
        issues_a = [{"type": "insufficient_sharpness", "severity": "high"}]
        issues_b = [{"type": "underexposure", "severity": "critical"}]

        r_a = calculate_analytics_readiness(q, issues_a)
        r_b = calculate_analytics_readiness(q, issues_b)

        # Both start from same quality but have different penalties
        assert r_a["base_quality_score"] == r_b["base_quality_score"] == 65.0
        # Penalties differ by issue type
        assert r_a["blur_penalty"] != r_b["exposure_penalty"] or r_a["score"] != r_b["score"]


# =========================================================================
# 3. Issue confidence comes from the detector
# =========================================================================

class TestIssueConfidence:
    """Verify that issue confidence is computed by detect_issues(), not hard-coded."""

    def test_confidence_values_from_detector(self):
        """detect_issues returns confidence values that reflect detection certainty."""
        # Clean image — no issues expected
        clean_features = {
            "sharpness": 200, "brightness": 128, "contrast": 50,
            "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
            "underexposure_pct": 2, "overexposure_pct": 1,
            "edge_density": 12, "dynamic_range": 150,
            "colorfulness": 30, "texture_complexity": 25,
        }
        issues = detect_issues(clean_features)
        assert len(issues) == 0

    def test_confidence_is_float_between_0_and_1(self):
        """All issue confidence values are floats in [0, 1]."""
        bad_features = {
            "sharpness": 3, "brightness": 30, "contrast": 8,
            "noise_estimate": 45, "entropy": 1.5, "saturation": 2,
            "underexposure_pct": 55, "overexposure_pct": 0,
            "edge_density": 0.3, "dynamic_range": 10,
            "colorfulness": 1, "texture_complexity": 0.3,
        }
        issues = detect_issues(bad_features)

        for issue in issues:
            assert "confidence" in issue
            assert 0.0 <= issue["confidence"] <= 1.0, (
                f"Issue '{issue['type']}' has confidence {issue['confidence']} "
                f"outside [0, 1]"
            )

    def test_confidence_varies_by_issue_type(self):
        """Different issue types have different confidence levels."""
        bad_features = {
            "sharpness": 3, "brightness": 30, "contrast": 8,
            "noise_estimate": 45, "entropy": 1.5, "saturation": 2,
            "underexposure_pct": 55, "overexposure_pct": 0,
            "edge_density": 0.3, "dynamic_range": 10,
            "colorfulness": 1, "texture_complexity": 0.3,
        }
        issues = detect_issues(bad_features)
        confidences = {i["type"]: i["confidence"] for i in issues}

        # severe_blur should have confidence 1.0 (deterministic threshold)
        if "severe_blur" in confidences:
            assert confidences["severe_blur"] == 1.0

        # image_noise should have confidence 1.0
        if "image_noise" in confidences:
            assert confidences["image_noise"] == 1.0

        # potential_visual_defect should have confidence 0.85
        if "potential_visual_defect" in confidences:
            assert confidences["potential_visual_defect"] == 0.85

    def test_issue_fields_contain_actual_metric_values(self):
        """Issues contain real metric value and threshold from detection."""
        features = {
            "sharpness": 25, "brightness": 100, "contrast": 40,
            "noise_estimate": 20, "entropy": 5, "saturation": 30,
            "underexposure_pct": 5, "overexposure_pct": 5,
            "edge_density": 8, "dynamic_range": 100,
            "colorfulness": 20, "texture_complexity": 20,
        }
        issues = detect_issues(features)

        for issue in issues:
            assert "metric" in issue
            assert "value" in issue
            assert "threshold" in issue
            assert isinstance(issue["value"], float)
            assert isinstance(issue["threshold"], float)

    def test_issue_value_reflects_actual_feature(self):
        """The 'value' in an issue matches the actual feature value."""
        features = {
            "sharpness": 25.0,
            "brightness": 60.0,
            "contrast": 40.0,
            "noise_estimate": 20.0,
            "entropy": 5.0,
            "saturation": 30.0,
            "underexposure_pct": 20.0,
            "overexposure_pct": 12.0,
            "edge_density": 8.0,
            "dynamic_range": 100.0,
            "colorfulness": 20.0,
            "texture_complexity": 20.0,
        }
        issues = detect_issues(features)

        # Find the sharpness issue
        sharpness_issues = [i for i in issues if i["metric"] == "laplacian_variance"]
        for si in sharpness_issues:
            assert si["value"] == 25.0, (
                f"Sharpness issue value {si['value']} != actual 25.0"
            )


# =========================================================================
# 4. No hard-coded production values
# =========================================================================

class TestNoHardCodedValues:
    """Verify no scores or recommendations are hard-coded in production code."""

    def test_backend_inference_has_no_hardcoded_scores(self):
        """predict_quality does not return a fixed score for all inputs."""
        results = []
        for brightness in [30, 100, 200]:
            for sharpness in [5, 100, 250]:
                feats = {"brightness": brightness, "contrast": 40, "sharpness": sharpness, "saturation": 30, "edge_density": 0.10}
                all_f = {"sharpness": sharpness, "brightness": brightness, "contrast": 40, "noise_estimate": 10, "entropy": 5,
                         "saturation": 30, "underexposure_pct": 5, "overexposure_pct": 5, "edge_density": 8, "dynamic_range": 80,
                         "colorfulness": 15, "texture_complexity": 15}
                result = predict_quality(feats, all_f)
                results.append(result["quality_score"])

        unique_scores = set(results)
        assert len(unique_scores) > 1, (
            f"predict_quality returned the same score for all inputs: {unique_scores}"
        )

    def test_readiness_is_not_copied_from_quality(self):
        """readiness_score ≠ quality_score when issues exist."""
        for qs in [30.0, 50.0, 70.0, 90.0]:
            issues = [{"type": "insufficient_sharpness", "severity": "high"}]
            readiness = calculate_analytics_readiness(qs, issues)
            assert readiness["score"] != qs, (
                f"Readiness {readiness['score']} should not equal quality {qs} "
                f"when blur issue is present"
            )

    def test_calculator_band_mapping_not_hardcoded_per_image(self):
        """Quality bands are defined globally, not per-image."""
        # All scores in [80, 100] should map to "Excellent"
        for score in [80, 85, 90, 95, 100]:
            assessment = get_quality_assessment(float(score))
            assert assessment["label"] == "Excellent"

        # All scores in [0, 19] should map to "Critical"
        for score in [0, 5, 10, 15, 19]:
            assessment = get_quality_assessment(float(score))
            assert assessment["label"] == "Critical"

    def test_recommendations_match_quality_bands(self):
        """Recommendations are derived from quality score, not image-specific."""
        for score in [90, 70, 50, 30, 10]:
            rec = get_quality_recommendation(float(score))
            assert isinstance(rec, str)
            assert len(rec) > 10

    def test_explainability_uses_actual_issue_data(self):
        """Explanations reference the actual issue's metric and threshold."""
        issues = [{
            "type": "image_noise",
            "severity": "high",
            "metric": "noise_estimate",
            "value": 22.5,
            "threshold": 15.0,
            "impact": "noise impact",
            "confidence": 1.0,
        }]
        explanations = generate_issue_explanations(issues)

        assert len(explanations) == 1
        exp = explanations[0]
        assert exp["evidence"]["metric"] == "noise_estimate"
        assert exp["evidence"]["value"] == 22.5
        assert exp["evidence"]["threshold"] == 15.0
        assert "noise" in exp["issue"].lower() or "noise" in exp["recommendation"].lower()

    def test_frontend_source_has_no_hardcoded_scores(self):
        """Production frontend components do not contain hard-coded scores."""
        frontend_dir = Path(__file__).parent.parent.parent / "frontend" / "src" / "components"
        if not frontend_dir.exists():
            pytest.skip("Frontend directory not found")

        # Components that should NOT have hard-coded scores
        component_files = [
            "analysis/AnalysisResult.tsx",
            "analysis/QualityScore.tsx",
            "analysis/IssueCard.tsx",
            "analysis/AnalyticsReadiness.tsx",
        ]

        for rel_path in component_files:
            fpath = frontend_dir / rel_path
            if not fpath.exists():
                continue
            content = fpath.read_text()
            # Should not contain hard-coded numeric scores
            # (exception: mathematical constants like 100 for /100)
            lines = content.split("\n")
            for i, line in enumerate(lines):
                stripped = line.strip()
                # Skip comments, imports, CSS values, SVG viewBox
                if stripped.startswith("//") or stripped.startswith("import") or "viewBox" in stripped:
                    continue
                # Check for patterns like quality_score: 85 or readiness: 42
                if any(pat in stripped for pat in ["quality_score:", "readiness_score:", "analysis_confidence:"]):
                    if any(c.isdigit() for c in stripped.split(":")[-1]):
                        pytest.fail(
                            f"Possible hard-coded score in {rel_path}:{i+1}: {stripped}"
                        )


# =========================================================================
# 5. Representative images produce logically different scores
# =========================================================================

class TestRepresentativeImageScores:
    """Analyze representative feature sets and verify logical score progression."""

    def _make_all_features(self, **overrides):
        """Create a full feature dict with sensible defaults, then override."""
        defaults = {
            "sharpness": 100, "brightness": 128, "contrast": 50,
            "noise_estimate": 10, "entropy": 6.0, "saturation": 35,
            "underexposure_pct": 3, "overexposure_pct": 2,
            "edge_density": 10, "dynamic_range": 120,
            "colorfulness": 25, "texture_complexity": 20,
        }
        defaults.update(overrides)
        return defaults

    def _analyze(self, features):
        model_feats = {k: features[k] for k in ["brightness", "contrast", "sharpness", "saturation", "edge_density"]}
        all_feats = features
        return predict_quality(model_feats, all_feats)

    def test_good_image_scores_higher_than_blurry(self):
        """A sharp image should score higher than a blurry one."""
        good = self._analyze(self._make_all_features(sharpness=250, brightness=130, contrast=55, noise_estimate=5))
        blurry = self._analyze(self._make_all_features(sharpness=10, brightness=130, contrast=55, noise_estimate=5))

        assert good["quality_score"] > blurry["quality_score"], (
            f"Good ({good['quality_score']}) should score higher than blurry ({blurry['quality_score']})"
        )

    def test_different_inputs_produce_different_scores(self):
        """Different feature sets produce different quality scores."""
        # Vary model-relevant features (brightness, contrast, sharpness, saturation, edge_density)
        a = self._analyze(self._make_all_features(brightness=128, sharpness=200, contrast=50, saturation=40, edge_density=25))
        b = self._analyze(self._make_all_features(brightness=30, sharpness=5, contrast=10, saturation=5, edge_density=1))

        assert a["quality_score"] != b["quality_score"], (
            f"Different inputs should produce different scores: a={a['quality_score']}, b={b['quality_score']}"
        )

    def test_extreme_features_differ_from_moderate(self):
        """Extreme feature values produce different scores from moderate ones."""
        moderate = self._analyze(self._make_all_features(brightness=200, sharpness=300, contrast=80, saturation=80, edge_density=30))
        extreme = self._analyze(self._make_all_features(brightness=20, sharpness=2, contrast=5, saturation=2, edge_density=0.5))

        assert moderate["quality_score"] != extreme["quality_score"], (
            f"Moderate ({moderate['quality_score']}) should differ from extreme ({extreme['quality_score']})"
        )

    def test_good_image_scores_higher_than_low_light(self):
        """A well-lit image should score higher than a low-light image."""
        lit = self._analyze(self._make_all_features(brightness=130, underexposure_pct=1))
        dark = self._analyze(self._make_all_features(brightness=35, underexposure_pct=50))

        assert lit["quality_score"] > dark["quality_score"]

    def test_readiness_degrades_with_more_issues(self):
        """More issues should reduce readiness score."""
        base_quality = 75.0

        r_clean = calculate_analytics_readiness(base_quality, [])
        r_one_issue = calculate_analytics_readiness(base_quality, [
            {"type": "insufficient_sharpness", "severity": "high"}
        ])
        r_many_issues = calculate_analytics_readiness(base_quality, [
            {"type": "insufficient_sharpness", "severity": "high"},
            {"type": "overexposure", "severity": "critical"},
            {"type": "image_noise", "severity": "high"},
        ])

        assert r_clean["score"] >= r_one_issue["score"] >= r_many_issues["score"]
        assert r_clean["score"] == base_quality  # No issues → no penalty

    def test_severity_affects_readiness_penalty(self):
        """Higher severity issues produce larger readiness penalties."""
        q = 80.0
        issues_low = [{"type": "insufficient_sharpness", "severity": "low"}]
        issues_high = [{"type": "insufficient_sharpness", "severity": "high"}]
        issues_critical = [{"type": "insufficient_sharpness", "severity": "critical"}]

        r_low = calculate_analytics_readiness(q, issues_low)
        r_high = calculate_analytics_readiness(q, issues_high)
        r_crit = calculate_analytics_readiness(q, issues_critical)

        assert r_low["score"] > r_high["score"] > r_crit["score"]
        assert r_low["blur_penalty"] < r_high["blur_penalty"] < r_crit["blur_penalty"]

    def test_context_impacts_vary_by_context(self):
        """Same issues produce different context impacts for different contexts."""
        issues = [{"type": "insufficient_sharpness", "severity": "high", "metric": "laplacian_variance",
                    "value": 30, "threshold": 40, "impact": "test", "confidence": 1.0}]

        impacts_traffic = get_context_impacts(issues, "Traffic Monitoring")
        impacts_crowd = get_context_impacts(issues, "Crowd Monitoring")

        # Both should have impacts for sharpness
        assert len(impacts_traffic) > 0
        assert len(impacts_crowd) > 0
        # But the text should differ
        assert impacts_traffic[0]["impact"] != impacts_crowd[0]["impact"]


# =========================================================================
# 6. Frontend displays exact API values
# =========================================================================

class TestFrontendDisplaysAPIValues:
    """Verify that the API response contains all fields the frontend expects."""

    def test_api_response_has_all_quality_fields(self):
        """POST /api/v1/analyze response contains all Phase 1 fields."""
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}
        result = predict_quality(features, all_feats)

        # Phase 1 fields
        assert isinstance(result["quality_score"], int)
        assert 0 <= result["quality_score"] <= 100
        assert result["quality_label"] in ["Excellent", "Good", "Fair", "Poor", "Critical"]
        assert isinstance(result["analysis_confidence"], float)
        assert 0 <= result["analysis_confidence"] <= 100
        assert isinstance(result["issues"], list)
        assert isinstance(result["statistics"], dict)
        assert isinstance(result["summary"], str)
        assert isinstance(result["recommendation"], str)

    def test_api_response_has_all_readiness_fields(self):
        """Response contains all Phase 3 analytics readiness fields."""
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}
        result = predict_quality(features, all_feats)

        assert "analytics_readiness_score" in result
        assert "analytics_readiness_status" in result
        assert "analytics_readiness_details" in result

        details = result["analytics_readiness_details"]
        assert "base_quality_score" in details
        assert "blur_penalty" in details
        assert "exposure_penalty" in details
        assert "noise_penalty" in details
        assert "corruption_penalty" in details
        assert "information_penalty" in details

    def test_api_response_has_all_context_fields(self):
        """Response contains Phase 4 context fields."""
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}
        result = predict_quality(features, all_feats, context="Traffic Monitoring")

        assert "context" in result
        assert result["context"] == "Traffic Monitoring"
        assert "context_impacts" in result
        assert isinstance(result["context_impacts"], list)

    def test_api_response_has_all_explainability_fields(self):
        """Response contains Phase 6 issue explanation fields."""
        all_feats = {"sharpness": 8, "brightness": 30, "contrast": 10, "noise_estimate": 40, "entropy": 2,
                     "saturation": 3, "underexposure_pct": 50, "overexposure_pct": 0,
                     "edge_density": 0.5, "dynamic_range": 15, "colorfulness": 1, "texture_complexity": 0.3}
        model_feats = {"brightness": 30, "contrast": 10, "sharpness": 8, "saturation": 3, "edge_density": 0.005}
        result = predict_quality(model_feats, all_feats)

        assert "issue_explanations" in result
        assert isinstance(result["issue_explanations"], list)

        if result["issue_explanations"]:
            exp = result["issue_explanations"][0]
            assert "issue" in exp
            assert "evidence" in exp
            assert "why_it_matters" in exp
            assert "recommendation" in exp
            assert "metric" in exp["evidence"]
            assert "value" in exp["evidence"]
            assert "threshold" in exp["evidence"]

    def test_issue_severity_matches_detector_constants(self):
        """All issue severities use the valid enum values."""
        all_feats = {"sharpness": 8, "brightness": 30, "contrast": 10, "noise_estimate": 40, "entropy": 2,
                     "saturation": 3, "underexposure_pct": 50, "overexposure_pct": 0,
                     "edge_density": 0.5, "dynamic_range": 15, "colorfulness": 1, "texture_complexity": 0.3}
        issues = detect_issues(all_feats)

        valid_severities = {"low", "moderate", "high", "critical"}
        for issue in issues:
            assert issue["severity"] in valid_severities, (
                f"Issue '{issue['type']}' has invalid severity '{issue['severity']}'"
            )

    def test_processing_time_is_dynamic(self):
        """processing_time_ms is measured, not a fixed value."""
        features = {"brightness": 128, "contrast": 50, "sharpness": 200, "saturation": 40, "edge_density": 0.15}
        all_feats = {"sharpness": 200, "brightness": 128, "contrast": 50, "noise_estimate": 5, "entropy": 6.5, "saturation": 40,
                     "underexposure_pct": 2, "overexposure_pct": 1, "edge_density": 12, "dynamic_range": 150, "colorfulness": 30, "texture_complexity": 25}
        result = predict_quality(features, all_feats)

        assert "processing_time_ms" in result
        assert isinstance(result["processing_time_ms"], int)
        assert result["processing_time_ms"] >= 0
